# Site settings
title: Derrek Sherman
name: Derrek Sherman

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/derreksherman
 - title: LinkedIn
   url: https://www.linkedin.com/in/derrek-sherman-85bb398a/

#Any buzzword skills you want to include
skills:
 - Java
 - Android Development
 - Computer Troubleshooting
 - Basic Devops

#Work experience is required
roles:
 - title: IT Technician
   start: 2018
   end: 2019
   employer: Office of Research Affairs UCSD
   description: Responsible for any technical issues affecting any organization under the ORA on UCSD campus supporting over 200 users. 
 - title: Network Operations Center Technician
   start: 2018
   end: 2018
   employer: XIFIN
   description: Rotating shift for monitoring network and service efforts and to provide a backup for other teams.
 - title: Network Technician
   start: 2011
   end: 2015
   employer: US Navy
   description: Maintained the operation of over 8,000 end point machines which included 412 Cisco routers and switches spanning over two separate networks.

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2021
   subject: Computer Science
   school: University of California, San Diego

#List of interesting Github repo/projects to include - optional
github:
 - cse112-sp20/CSE112-Neon

intro: |
  I am currently a CS Student at UCSD. I used to work in the IT industry(mostly for the Navy) but have decided to move on to software development.<br/><br/>
  I enjoy poking my fingers at different technologies. I enjoy the outdoors, Dungeons and Dragons, and video games.<br/><br/>

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Java</strong>: I have taken many classes centered around using java and various frameworks and Android devolopment <br/><br/>
   <strong>Software Development</strong>: Taken several software devolopment classes geared towards working in teams and using correct software dev process.<br/><br/>
   <strong>Pipeline</strong>: Experianced using several tools for pipelines and CI. Github Actions, Travis, Jenkins, Github, Git, Code Climate <br/><br/>
   <strong>Computer Knowledge</strong>: My background in IT gives me some solid experiance to fall back on in all things related to computers eg: Bash, Powershell, WSL, Active Directory, Networking(OSPF, STP, etc) <br/><br/>
   <strong>Worthy Mentions </strong>: Some technologies I may have tinkered with or only taken one class with include C++, C, Assembly, Rust, Node JS, Electron, HTML, JS, Python <br/><br/>
